### ISSUE TITLE
[Bug]: Mobs spawned by base mod are not affected by Reaper Gen

### ISSUE THREAD

**Issue by ImMorphi** [terrarium-earth/Reaper#4]
### Bug Description

The Mobs that are spawned in via a Soul Cage in the base mod (Spirit) seem to be unaffected by the reaper generator.

### How to Reproduce?

1. Create a soul cage with any mob
2. Set up reaper generator
3. Observe

### Expected Behavior

The mobs spawned in via the soul cage would be killed and energy extracted.

### Version

1.0.4

### Mod Loader Version

1.19.2

### Mod Loader

Fabric

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by CodexAdrian** [comment]
This is not a bug
